name: Deploy

on: 
  push:
    branches:
      - master
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:    
      - name: checkout
        uses: actions/checkout@v4

      - name: setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # - name: create file
      #   run: ssh -o StrictHostKeyChecking=no azureuser@20.55.28.37 touch hola.txt
      
      - name: Deploy to stage server
        if: "${{ github.ref == 'refs/heads/stage' }}"
        run: bash deploy.sh stage
      
      - name: Deploy to prod server
        if: "${{ github.ref == 'refs/heads/master' }}"
        run: bash deploy.sh master


